name: Fix Specs

on:
  workflow_call:
    inputs:
      summary:
        required: true
        type: string

jobs:
  fix-specs:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install CodeMie CLI
        run: npm install -g @codemieai/code

      - name: Run codemie-code basic command
        run: |
          codemie auth status
          echo ${{ inputs.summary }}
          codemie profile login
          codemie-code --model claude-4-1-opus --task "Install concurrently dev dependency in package.json"
          git status
